site_name: Yassin Siouda
site_url: https://yassin.siouda.com
site_author: Yassin Siouda
nav:
    - Home: index.md
    - Projects: projects/projects.md
    - Events: events/events.md
    - Articles: articles/articles.md
    - About: about/about.md
theme: 
    name: material
    logo: 
    font:
        text: Red Hat Mono
    palette: 
        primary: black
        accent: black
    plugins:
        - tags
    
extra:
    generator: false
    
docs_dir: src

